version: '2'
services:
  db:
    image: postgres
    container_name: ofpl-db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    restart: always
  es:
    image: elasticsearch
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    expose:
      - "9200"
    restart: always
  web:
    build:
      context: ./web
      args:
        env: prod
    command: sh -c "python manage.py collectstatic --noinput; gunicorn config.wsgi:application --name ofpl --bind 0.0.0.0:8000 --workers 3 --reload"
    environment:
     - DJANGO_SETTINGS_MODULE=config.settings.prod
    volumes:
      - ./web:/app
      - ./static:/static
      - ./media:/media
    depends_on:
      - db
      - es
    ports:
      - "8000:8000"
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "8084:8084"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
    restart: always

volumes:
  db-data:
  es-data:
