# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161129_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='link_external',
            field=models.URLField(blank=True, verbose_name='External Link'),
        ),
    ]
