# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_redirectpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
    ]
