# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20170103_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoursList',
        ),
    ]
