# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alert_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
