# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 09:33
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20170112_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='center_column',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_column',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
