# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'events',
                'ordering': ('title',),
                'verbose_name': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4, unique=True, verbose_name='abbreviation')),
                ('label', models.CharField(max_length=50, verbose_name='label')),
            ],
            options={
                'verbose_name_plural': 'event types',
                'verbose_name': 'event type',
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='calendar.Event', verbose_name='event')),
            ],
            options={
                'verbose_name_plural': 'occurrences',
                'ordering': ('start_time', 'end_time'),
                'verbose_name': 'occurrence',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.EventType', verbose_name='event type'),
        ),
    ]
