# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 04:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='event',
            field=modelcluster.fields.ParentalKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='calendar.Event', verbose_name='event'),
        ),
    ]
