# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0005_auto_20170109_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page_skin',
            field=models.CharField(choices=[(' ', 'Default'), ('kids', 'Kids'), ('teens', 'Teens')], default=' ', max_length=255),
        ),
    ]
