# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_auto_20170112_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarIndexPageSingleton',
            new_name='EventRootSingleton',
        ),
    ]
