# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0008_auto_20170112_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendargridpage',
            name='event_types',
            field=models.ManyToManyField(to='calendar.EventType'),
        ),
        migrations.AddField(
            model_name='calendargridpage',
            name='page_skin',
            field=models.CharField(choices=[(' ', 'Default'), ('kids', 'Kids'), ('teens', 'Teens')], default=' ', max_length=255),
        ),
    ]
