# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0009_auto_20170112_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendargridpage',
            name='event_types',
        ),
    ]
