# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 22:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0011_occurrence_display_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='what',
            field=wagtail.wagtailcore.fields.RichTextField(default=wagtail.wagtailcore.fields.RichTextField()),
        ),
        migrations.AddField(
            model_name='event',
            name='when',
            field=wagtail.wagtailcore.fields.RichTextField(default=wagtail.wagtailcore.fields.RichTextField()),
        ),
        migrations.AddField(
            model_name='event',
            name='where',
            field=wagtail.wagtailcore.fields.RichTextField(default=wagtail.wagtailcore.fields.RichTextField()),
        ),
        migrations.AddField(
            model_name='event',
            name='who',
            field=wagtail.wagtailcore.fields.RichTextField(default=wagtail.wagtailcore.fields.RichTextField()),
        ),
    ]
