# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0012_auto_20170112_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
    ]
