# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0013_event_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
