# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('calendar', '0015_auto_20170113_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStreamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_skin', models.CharField(choices=[(' ', 'Default'), ('kids', 'Kids'), ('teens', 'Teens')], default=' ', max_length=255)),
                ('content', wagtail.wagtailcore.fields.RichTextField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar.EventType', verbose_name='event type')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
