# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0017_auto_20170118_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventstreampage',
            old_name='event_type',
            new_name='type',
        ),
    ]
